### ISSUE TITLE
Too few intervals and at least 3 but get 2 only

### ISSUE THREAD

**Issue by yugao0912** [virocon-organization/virocon#168] opened 2023-02-19 19:16 UTC
When I was trying to run the 3D_Contour using my data it always shows that there were ‘too few intervals at least 3 but get 2 only’—additionally same problem with wind-wave contour.

  File "E:\Python\lib\site-packages\virocon\intervals.py", line 67, in slice_
    raise RuntimeError(

RuntimeError: Slicing resulting in too few intervals. Need at least 3, but got only 2 intervals.

I guess it’s because my data format and the exponential Weibull distribution doesn’t support my data after a series of comparison. Once I use my data sources, the virocon can not be available. Are there any mistakes with my data?

Thank you.

Yu

**Comment by ahaselsteiner** [comment] 2023-02-20 13:20
Hi Yu! Thanks for posting the problem as a GitHub issue here.

I want to solve the problem with you.

Could you post your data file here so that I can reproduce the error?

**Comment by yugao0912** [comment] 2023-02-20 13:46
Hi Andreas,

Of course, please see attached. The ‘test.csv’ is for 3D-Contour, and WIND-WAVE DATA is for the Wind-Wave contour.

It seems that the files can not be sent by email. I have no idea whether they are available here. But I am trying to post them.

Thank you for your help.

Best regards
Gao Yu
[WIND-WAVE DATA USED.xlsx](https://github.com/virocon-organization/virocon/files/10784965/WIND-WAVE.DATA.USED.xlsx)
[WIND-WAVE DATA USED.txt](https://github.com/virocon-organization/virocon/files/10784966/WIND-WAVE.DATA.USED.txt)
[test.csv](https://github.com/virocon-organization/virocon/files/10784967/test.csv)

**Comment by ahaselsteiner** [comment] 2023-02-21 17:03
@yugao0912 I took a look at your wind-wave dataset. In order to get more than 2 intervals I reduced the interval width from 2 m/s to 0.5 m/s.

Here is the script I used (I moved your dataset in the "datasets" folder):

```
"""
Example with Yu's data for a wind speed - wave height contour.
"""
import matplotlib.pyplot as plt
from virocon import (
    read_ec_benchmark_dataset,
    get_OMAE2020_V_Hs,
    GlobalHierarchicalModel,
    IFORMContour,
    plot_2D_contour,
    ExponentiatedWeibullDistribution,
    WidthOfIntervalSlicer
)

# Load wind speed - wave height hindcast dataset.
data = read_ec_benchmark_dataset("datasets/WIND-WAVE.DATA.USED.txt")

# Define the structure of the joint distribution model.
dist_descriptions, fit_descriptions, semantics = get_OMAE2020_V_Hs()

# Let's use smaller intervals than in the OMAE2020 model
dist_description_v = {
    "distribution": ExponentiatedWeibullDistribution(),
    "intervals": WidthOfIntervalSlicer(0.5, min_n_points=10),
}

dist_descriptions_for_yu = [dist_description_v, dist_descriptions[0]]
model = GlobalHierarchicalModel(dist_descriptions_for_yu)

# Estimate the model's parameter values (fitting).
model.fit(data, fit_descriptions=fit_descriptions)

# Compute an IFORM contour with a return period of 50 years.
tr = 50  # Return period in years.
ts = 1  # Sea state duration in hours.
alpha = 1 / (tr * 365.25 * 24 / ts)
contour = IFORMContour(model, alpha)

# Plot the contour.
plot_2D_contour(contour, data, semantics=semantics)
plt.show()
```

This the contour I get:

![YuContour](https://user-images.githubusercontent.com/11452055/220411126-a30faed3-4924-457b-9796-44e67bfc009f.png)


However, your dataset looks strange. There are significant wave heights up to 15 m while the wind speed has a maximum of 4.5 m/s

Did you swap the wind speed and wave height columns?

**Comment by yugao0912** [comment] 2023-02-21 17:14
Hello Andreas, 

Thank you for helping me. I am sorry for that I forgot to change the information in the first row. I suppose the second column is the wind speed, and the first conlumn is wave height.

[WIND-WAVE.DATA.USED.xlsx](https://github.com/virocon-organization/virocon/files/10795879/WIND-WAVE.DATA.USED.xlsx)

Additionally, I am not very clear about where are the errors. Is it in the file named intervals?

Best,
Yu

**Comment by ahaselsteiner** [comment] 2023-02-21 17:21
Which errors are you referring to?

**Comment by yugao0912** [comment] 2023-02-21 17:31
Sorry, I mean I would like to know where to modify the code to ensure that the 'intervals too few' problem does not occur again. I have tried to modify it but I am a bit confused because I just started to learn the programming not long.
Or I could just use the program you used in the comments?

**Comment by ahaselsteiner** [comment] 2023-02-22 14:15
No worries :-)

The problem occurred because the standard OMAE 2020 model uses an interval width of 2 m/s for wind speed. 

In virocon using an interval width of 2 m/s is defined in this way:

```
dist_description_v = {
    "distribution": ExponentiatedWeibullDistribution(),
    "intervals": WidthOfIntervalSlicer(2, min_n_points=50),
}
```

You can find the definition here: https://github.com/virocon-organization/virocon/blob/master/virocon/predefined.py#L268

Your wind speed data (which actually was wave height data) had only wind speeds up to 5.5 m/s so there were only 2 viable intervals. However, virocon needs at least 3 intervals for fitting. Consequently, you got the error message.

To solve the problem I changed the interval size in the code I posted.

I changed it to use an interval size of 0.5 m/s and defined that we only need at least 10 data points per interval.

```
dist_description_v = {
    "distribution": ExponentiatedWeibullDistribution(),
    "intervals": WidthOfIntervalSlicer(0.5, min_n_points=10),
}
```

You can use this definition for your use case too.

However, I think you can just go with the standard settings (2 m/s interval width) when you put your wind speed and wave height columns in the right order.

**Comment by yugao0912** [comment] 2023-02-24 13:19
Dear Andreas,

I have adjusted the data to put them in right order, but I got the contour as below.

![image](https://user-images.githubusercontent.com/125657072/221188140-bc6a5a12-8023-4c07-8cfc-1df3e8d61d52.png)

I am wondering if the metocean data is not very suitale as it looks a little weired.

Best regards,
Yu

**Comment by ahaselsteiner** [comment] 2023-02-24 16:01
What is it that you don't like about the contour? That it has a high-Hs peak at low wind speeds?

I think the way forward would be to explore the goodness of fit of the fitted joint distribution model. 

In this paper, we applied a couple of different methods to analyze joint distribution models and contours: https://www.sciencedirect.com/science/article/pii/S0029801821009033

It might give you ideas on how you could analyze the fit of your distribution and the appropriateness of the contour.

**Comment by yugao0912** [comment] 2023-02-25 23:45
Hello Andreas,

I am sorry for my late respond. Yes, I think it is not very accurate that there is a high wave height at low wind speeds. The reason why I doubt the my data is that there always are very long period like 30 or 40 sec with extreme low wave height at the 50-year contour or 100-year contour when I use Wave-period contour method. 

Many thanks for your suggestion. I will read relative literatures as you mentioned.

Best regards,
Yu

**Comment by ahaselsteiner** [comment] 2023-12-16 22:02
@yugao0912 I hope you were able to build a proper model and calculate an appropriate contour. I am closing this issue.

**Closed by ahaselsteiner** 2023-12-16 22:02 UTC
Labels: wontfix, user feedback
